### PR TITLE
fix(generate): component generation fixed for many catalogs

### LINKED ISSUE #571: Generate Component failing with fedramp catalog
### Steps to reproduce
```bash
dev@dev:~/work/lula$ ./bin/lula generate component -c https://raw.githubusercontent.com/GSA/fedramp-automation/93ca0e20ff5e54fc04140613476fba80f08e3c7d/dist/content/rev5/baselines/json/FedRAMP_rev5_HIGH-baseline-resolved-profile_catalog.json --component "Istio Controlplane" -r ac-14,ac-4,ac-4.21,ac-4.4,ac-6.3,ac-6.9,au-12,au-2,au-3,au-3.1,cm-5,sc-10,sc-13,sc-23,sc-3,sc-39,sc-4,sc-7.20,sc-7.21,sc-7.4,sc-7.8,sc-8,sc-8.1,sc-8.2
```

### Expected result
Successful component generation

### Actual Result

```bash
 NOTE  Saving log file to /tmp/lula-2024-07-31-15-06-34-3505079792.log
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c2dcfb]

goroutine 1 [running]:
github.com/defenseunicorns/lula/src/pkg/common/oscal.addPart(0xc00096fb80?, 0xc004afb498, 0x0)
        github.com/defenseunicorns/lula/src/pkg/common/oscal/component.go:524 +0xbb
github.com/defenseunicorns/lula/src/pkg/common/oscal.ControlToImplementedRequirement(0xc004afb5e8, {0xc004afbc40, 0x1, 0x0?})
        github.com/defenseunicorns/lula/src/pkg/common/oscal/component.go:376 +0x3e5
github.com/defenseunicorns/lula/src/pkg/common/oscal.ComponentFromCatalog({0x7fff77eef2ca, 0xbb}, 0xc000f18000, {0x7fff77eef392, 0x12}, {0xc000ac6d80, 0x18, 0xc79e9c5400000000?}, {0xc004afbc40, 0x1, ...})
        github.com/defenseunicorns/lula/src/pkg/common/oscal/component.go:282 +0xbd8
github.com/defenseunicorns/lula/src/cmd/generate.init.func1(0x3a94e00, {0xc0000ede00?, 0x4?, 0x2192ad3?})
        github.com/defenseunicorns/lula/src/cmd/generate/generate.go:107 +0x445
github.com/spf13/cobra.(*Command).execute(0x3a94e00, {0xc0000eda40, 0x6, 0x6})
        github.com/spf13/cobra@v1.8.1/command.go:989 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0x3a93fa0)
        github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/defenseunicorns/lula/src/cmd.Execute()
        github.com/defenseunicorns/lula/src/cmd/root.go:57 +0x1a
main.main()
        github.com/defenseunicorns/lula/main.go:8 +0xf
```

### Severity/Priority
Medium

### Additional Context
May need to keep considering if there is any functionality too opinionated for 800-53 that does not work with generic catalog authorship.

### PR DESCRIPTION
**Pull request by brandtkeller**
## Description

This fixes a nil pointer dereference error caught while testing the fedramp catalog generation.

This also includes much better depth of control enumeration given how groups and controls can be potentially nested in catalogs. 

## Testing Targets

Outside of the unit testing for generation functionality - catalogs that can be used for testing:

```
https://raw.githubusercontent.com/usnistgov/oscal-content/main/examples/catalog/json/basic-catalog.json
```

```
https://raw.githubusercontent.com/GSA/fedramp-automation/93ca0e20ff5e54fc04140613476fba80f08e3c7d/dist/content/rev5/baselines/json/FedRAMP_rev5_HIGH-baseline-resolved-profile_catalog.json
```

```
https://raw.githubusercontent.com/usnistgov/oscal-content/main/nist.gov/SP800-53/rev5/json/NIST_SP-800-53_rev5_catalog.json
```
## Related Issue

Fixes #571 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Schema Updates](https://github.com/defenseunicorns/lula/blob/main/docs/community-and-contribution/schema-updates.md) applied
- [x] [Contributor Guide Steps](https://github.com/defenseunicorns/lula/blob/main/CONTRIBUTING.md) followed

### CODE REVIEW

**Comment by meganwolf0** [comment]
I tried with the basic-catalog and got the following
```
❯ lula generate component -c https://raw.githubusercontent.com/usnistgov/oscal-content/main/examples/catalog/json/basic-catalog.json -r s1.1.1  -l debug   
  DEBUG   2024-08-02T13:14:14-04:00  -  Log level set to debug

 NOTE  Saving log file to
       /var/folders/6t/7mh42zsx6yv_3qzw2sfyh5f80000gn/T/lula-2024-08-02-13-14-14-2093984482.log
  DEBUG   2024-08-02T13:14:14-04:00  -  jsonschema: '' does not validate with http://csrc.nist.gov/ns/oscal/1.0/1.1.2/oscal-complete-schema.json#/oneOf/0/required: missing properties: 'catalog'
     ERROR:  error writing component to file
  DEBUG   2024-08-02T13:14:14-04:00  -  goroutine 1 [running]:
          runtime/debug.Stack()
                runtime/debug/stack.go:24 +0x64
          github.com/defenseunicorns/lula/src/pkg/message.Fatal({0x102718240?, 0x14000a4a960?}, {0x1400005a400, 0x1f})
                github.com/defenseunicorns/lula/src/pkg/message/message.go:169 +0x11c
          github.com/defenseunicorns/lula/src/pkg/message.Fatalf({0x102718240, 0x14000a4a960}, {0x101c75644?, 0x1?}, {0x0?, 0x140009e9b70?, 0x1?})
                github.com/defenseunicorns/lula/src/pkg/message/message.go:176 +0x78
          github.com/defenseunicorns/lula/src/cmd/generate.init.func1(0x103a65020, {0x14000114ae0?, 0x4?, 0x101c3f437?})
                github.com/defenseunicorns/lula/src/cmd/generate/generate.go:123 +0x4bc
          github.com/spf13/cobra.(*Command).execute(0x103a65020, {0x14000114a80, 0x6, 0x6})
                github.com/spf13/cobra@v1.8.1/command.go:989 +0x828
          github.com/spf13/cobra.(*Command).ExecuteC(0x103a641c0)
                github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
          github.com/spf13/cobra.(*Command).Execute(...)
                github.com/spf13/cobra@v1.8.1/command.go:1041
          github.com/defenseunicorns/lula/src/cmd.Execute()
                github.com/defenseunicorns/lula/src/cmd/root.go:57 +0x24
          main.main()
                github.com/defenseunicorns/lula/main.go:8 +0x1c
```

Is that expected? Seems like the basic catalog isn't providing some required data for the component-definition to be properly constructed (the error seems to indicate it's missing `catalog` though which doesn't make a ton of sense since that was the input?)

**Comment by brandtkeller** [comment]
> I tried with the basic-catalog and got the following
> ...
> Is that expected? Seems like the basic catalog isn't providing some required data for the component-definition to be properly constructed (the error seems to indicate it's missing `catalog` though which doesn't make a ton of sense since that was the input?)

That error is indicating a problem writing to a file - and given that a validation error is occurring - is there any chance you attempted to write this output (possibly the default file output) to a pre-existing and non-valid file?

**Comment by meganwolf0** [comment]
> is there any chance you attempted to write this output (possibly the default file output) to a pre-existing and non-valid file?

Ok yep I went back and reviewed the commands I used - 
First I ran this
```
lula generate component -c https://raw.githubusercontent.com/usnistgov/oscal-content/main/examples/catalog/json/basic-catalog.json -r s1 -l debug
```
Which output a `component.yaml` but there were no implemented requirements since `s1` is not valid. I then ran:
```
lula generate component -c https://raw.githubusercontent.com/usnistgov/oscal-content/main/examples/catalog/json/basic-catalog.json -r s1.1.1 -l debug
```
Which tries to write to the same component-definition, but I guess is hitting that error that the file is invalid? Which is sort of weird because it was written the first time around... Definitely an edge case, but looks like the initial command output an invalid file or something.

**Comment by brandtkeller** [comment]
> Which tries to write to the same component-definition, but I guess is hitting that error that the file is invalid? Which is sort of weird because it was written the first time around... Definitely an edge case, but looks like the initial command output an invalid file or something.

Agreed - I'll look at fixing some of this behavior.

**Comment by brandtkeller** [comment]
@meganwolf0 We now verify that at least one control was identified before the creation of the file otherwise producing an error that no controls could be found. 

This should prevent the issue you saw before.

**Review by meganwolf0 — APPROVED** [review]

**Pull request merged**
