### PR TITLE
Lula payload location

### LINKED ISSUE #15: OSCAL Schema compliance for extended oscal component definition
Update the oscal-component.yaml documents and surrounding logic to be compliant with OSCAL schema.

### PR DESCRIPTION
**Pull request by brandtkeller**
First iteration and closes #15 

Introduces one possible solution towards the goal of "OSCAL native" - Being that the prescribed method of the lula payload inclusion in the Component Definition OSCAL document is now using valid schema.

## optimizations
- This solution provides a mechanism for caching previous evaluations given a primary `UUID` identifier. Given that some validations may be duplicate across control groups we may gain some efficiency here.

### Notes
- `target` was added as the root of the overall payload. Language can change here but it's primarily as a workaround for trying to template yaml from a string.
  - This allows us to remove duplicate types from Lula entirely (and pull them directly from `go-oscal`.

### CODE REVIEW

**Comment by brandtkeller** [comment]
Migrated to using upstream oscal component definition types.

**Review by Alvin-zzz — DISMISSED** [review]
LGTM, we are one step closer.

**Review by CloudBeard — DISMISSED** [review]
Oops wrong PR, ignore my comments.

**Review by CloudBeard — APPROVED** [review]
Tested locally with no issues.

**Pull request merged**
