### PR TITLE
fix: simplify api test dependencies

### PR DESCRIPTION
**Pull request by brandtkeller**
Looking to see if there are ways to optimize the testing of the API provider by reducing the dependencies given the current constraints (or lack-thereof). 

By removing ingress and allocating hostport on the test pod directly we can still execute the API request. 

This reduces the github action time from [4:39](https://github.com/defenseunicorns/lula/actions/runs/6894497657/job/18756427043) to [2:45](https://github.com/defenseunicorns/lula/actions/runs/6897558773/job/18765955268?pr=117) for the E2E Testing check.

### CODE REVIEW

**Comment by brandtkeller** [comment]
Would love feedback from @TheFutonEng and @btlghrants

**Review by btlghrants — DISMISSED** [review]
LGTM.

Given the current scenarios -- and how we chatted through the viability of publishing one-or-more routes back into the nginx.conf -- I think this one's a win.

**Comment by TheFutonEng** [comment]
I agree with this PR as well.  Reducing the cycle time at this stage of development is a clear win.

**Review by CloudBeard — APPROVED** [review]
LGTM

**Pull request merged**
