### PR TITLE
fix(gen-cli-docs): fix path for gen-cli-docs

### LINKED ISSUE #645: Broken links in cli command docs
### Steps to reproduce
1. visit a command containing subcommands [example](https://docs.lula.dev/cli-commands/lula_dev/)
2. click on one of the subcommand links
  
### Expected result

Route to the subcommand documentations

### Actual Result

404

### Severity/Priority

Medium

### Additional Context

Need to update the `gen-cli-command`

### PR DESCRIPTION
**Pull request by brandtkeller**
## Description

Update the `gen-cli-docs` command to generate links that the docs website will resolve. The reference needs to originate from root ie `/cli-commands/<command>`

## Related Issue

Fixes #645 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Schema Updates](https://github.com/defenseunicorns/lula/blob/main/docs/community-and-contribution/schema-updates.md) applied
- [x] [Contributor Guide Steps](https://github.com/defenseunicorns/lula/blob/main/CONTRIBUTING.md) followed

### CODE REVIEW

**Comment by meganwolf0** [comment]
are these supposed to be links to the `*.md` documents? (I think the urls would just be the name of the file, no?)

**Comment by brandtkeller** [comment]
> are these supposed to be links to the `*.md` documents? (I think the urls would just be the name of the file, no?)

These are links to the resolvable page in the docs website minus the base URL `docs.lula.dev`

Example: 

`docs.lula.dev` + `/cli-commands/lula_dev/` would route to the page accordingly. 

the current `/cli` was an oversight and that obviously (in hindsight) doesn't route properly.

**Comment by meganwolf0** [comment]
If you just do like ./name.md though wouldn't that be handled by the Lula-docs code and also be a usable link in the repo?

**Comment by brandtkeller** [comment]
> If you just do like ./name.md though wouldn't that be handled by the Lula-docs code and also be a usable link in the repo?

It could be - this is where more testing with lula-docs interpretation is required. I was simply noting the delta between current link and routing and fixing accordingly.

**Comment by meganwolf0** [comment]
> It could be - this is where more testing with lula-docs interpretation is required. I was simply noting the delta between current link and routing and fixing accordingly.

If you see the README.md in `getting-started` it has a relative link to `./simple-demo.md` which is properly handled by the [website](https://docs.lula.dev/getting-started/#tutorials). So I guess this is really a matter of if we want the links to work both in the lula repo and on the site - if yes then maybe we update to just point to the file name and if the logic is consistent it should remap to the site correctly

**Comment by brandtkeller** [comment]
> If you see the README.md in `getting-started` it has a relative link to `./simple-demo.md` which is properly handled by the [website](https://docs.lula.dev/getting-started/#tutorials). So I guess this is really a matter of if we want the links to work both in the lula repo and on the site - if yes then maybe we update to just point to the file name and if the logic is consistent it should remap to the site correctly

Great point - provided the docs infrastructure (hugo) does allow those relative links (as you've indicated) then updating to support both is pretty trivial given the flat structure. Updated accordingly.

**Review by meganwolf0 — APPROVED** [review]

**Pull request merged**
